[PKG-5391] Update to 2.4.2
AnacondaRecipes/sacrebleu-feedstock pull request #3
Opened 2024-08-14 19:26 UTC by ViridianMelody

sacrebleu 2.4.2

**Destination channel:** defaults

### Links

- [PKG-5391]
- [Upstream repository](https://github.com/mjpost/sacrebleu)
- [Upstream changelog/diff]()

### Explanation of changes:

- Removed obsolete `setup.py` patch.
- Added upstream tests.
- Switch to Github source, since source wasn't uploaded to Pypi.

2024-08-14 19:27 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_a86amucyxh/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:61: missing_license_family: The recipe is missing the `about/license_family` key.
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-15 18:58 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_1fctw28a38/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:20: patch_unnecessary: patch should not be in build when source/patches is not set
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-20 08:40 UTC, boldorider4 commented on recipe/meta.yaml
> +{% set version = "2.4.2" %}
`2.4.3` is out.

2024-08-20 08:40 UTC, boldorider4 approved these changes
LGTM but could be upgraded to `2.4.3`

2024-08-20 23:04 UTC, Jrice1317 requested changes

2024-08-20 23:04 UTC, Jrice1317 commented on recipe/meta.yaml
> +  url: https://github.com/mjpost/sacrebleu/archive/refs/tags/v{{ version }}.tar.gz
I'm curious the reason for switching the source to the github url?

2024-08-20 23:04 UTC, Jrice1317 commented on recipe/meta.yaml
> +  url: https://github.com/mjpost/sacrebleu/archive/refs/tags/v{{ version }}.tar.gz
I just noticed your comment in the description, but maybe updating to `2.4.3` will remove the issue as it seems to be listed [here](https://inspector.pypi.io/project/sacrebleu/)

2024-08-22 15:56 UTC, Jrice1317 commented on recipe/meta.yaml
> +    - mecab-ko-dic >=1.0,>2.0
```suggestion
    - mecab-python3 >=1.0.9,<2.0.0
    - mecab-ko >=1.0.0,<=1.0.1
    - mecab-ko-dic >=1.0,<2.0
```

2024-08-22 19:22 UTC, Jrice1317 approved these changes

2024-08-22 20:07 UTC, merged